### ISSUE TITLE
Cannot connect a third camera

### ISSUE THREAD

**Issue by Robkivit** [martijnpoppen/com.eufylife.security#19]
I like you app very much and it works great with homey ! I have noticed a few issues:
- I cannot add a third camera eufy 2c pro within homey. After installation the app only display the first two camera's: deurbel en camera 2c pro. I have restarted the app, clean and deinstalled the app but it still displays only the 2 cameras 
- the camera eufy 2c pro only detect motions but not react on persons in a homey flow

Hope you can help me with this possible issues 

Thanks and keep on the good work!

Kind regards,
Rob Kivit

**Comment by martijnpoppen** [comment]
Hi Rob,
Best way to check would be if you could enable DEBUG in the settings and send met your ACTOR_ID. Then I can have a look at the logs.

**Comment by martijnpoppen** [comment]
Hi Rob,
- Adding a extra camera is poossible now. Found the issue for this. 
- To detect persons you have to enable this in the detection settings of eufy

**Comment by Robkivit** [comment]
Hi Martijn,
Ontzettend bedankt!
Alleen voor het onderscheid maken tussen beweging en personen reageert de camera alleen op beweging ondanks dat de eufy op alleen op het detecteren van personen staat ingesteld. Ik heb dat getest met 2 aparte flows.

Misschien vind je hier nog een oplossing voor

Nogmaals dank!


Groeten, Rob

**Comment by martijnpoppen** [comment]
Hi @Robkivit ,
Gek dat dat niet werkt. Ik kan even voor je kijken in de logs van jouw eufy homey app. Als je DEBUG aanzet in de instellingen en mij je ACTOR_ID stuurt.   Dit vind je bij Apps -> Eufy Security -> configureer app.

**Comment by Robkivit** [comment]
Martijn,
Ik heb thuis een eufy deurbel en 2x cam 2c pro camera’s. 
Als ik vervolgens in homey bij apparaat toevoegen kies voor eufy security app en vervolgens eufy cam 2c pro installeer dan wordt alleen de deurbel getoond ipv alle 3 de camera’s. Wellicht komt het hierdoor dat voor beweging en personen altijd status van beweging wordt doorgegeven 



Groeten, Rob

**Comment by martijnpoppen** [comment]
Hoi Rob,
Het is voor mij erg lastig te zien wat er misgaat zonder dat ik de logs kan zien. Elke camera heeft zijn eigen eigenschappen en zal daarom ook op een andere manier werken.

Zoals eerder aangegeven kan ik meekijken in de logs. Mocht je dat niet willen geef dat vooral aan. 
Maar in dat geval word het erg lastig om na te gaan wat er misgaat.

**Comment by Robkivit** [comment]
Martijn,
Ik zal het even aanzetten en geef je een seintje
Ik zie overigens dat voor toevoegen apparaten alleen bij eufycam 2c pro niet alle camera’s worden worden getoond; bij de overige typen worden wel alle 3x camera getoond

Groeten, Rob

**Comment by Robkivit** [comment]
Marijn,
De logging aan
Actor id: c9fadf510f70a3368a05c7b99394561f202446fe

Bedankt!


Groeten, Rob

**Comment by martijnpoppen** [comment]
Hoi Rob,
Op welke app versie zit je?

**Comment by martijnpoppen** [comment]
Ik zie al iets wat niet goed staat. Je local_station_ip staat ingesteld op een publiek ip ipv een lokaal ip.
Dit kan je aanpassen bij  Apps -> Eufy Security -> configureer app.
Vul daar het lokale IP van je homebase in

**Comment by Robkivit** [comment]
Martijn,
Ik heb het ip adres gewijzigd naar het op adres vd homebase maar ik bij het installeren vd app nog steeds alleen de deurbel ipv alle 3


Groeten, Rob

**Comment by Robkivit** [comment]
Martijn,
Versie 1.6.3


Groeten, Rob

**Comment by martijnpoppen** [comment]
Ik heb 1.8.6 in test staan: https://homey.app/nl-nl/app/com.eufylife.security/Eufy-Security/test/
Zou je die kunnen installeren?

**Comment by Robkivit** [comment]
Martijn,
Nieuwe versie geïnstalleerd en gechecked maar bij installeren van een apparaat kunnen nu geen devices worse gevonden 



Groeten, Rob

**Comment by martijnpoppen** [comment]
Hoi Rob,
Ja dat klopt. 
Ik dacht al dat het daarom mis ging.
In deze versie checkt hij of de apparaten al verbonden zijn. 
Alle 3 de camera's zijn al toegevoegd aan je Homey namelijk.

**Comment by martijnpoppen** [comment]
Ik zie een camera terras, camera deurbel en camera achtertuin als verbonden apparaten

**Comment by Robkivit** [comment]
Martijn,
Dat klopt idd
Ik was in de veronderstelling dat bij het installeren alle beschikbare devices werden getoond welke afzonderlijk konden aan/uitgevinkt 


Groeten, Rob

**Comment by martijnpoppen** [comment]
Wat betreft beweging en persoons detectie.

Voor persoondetectie kan je het beste de instellingen als volgt hebben in je Eufy App:

![WhatsApp Image 2021-01-08 at 15 35 39](https://user-images.githubusercontent.com/7694138/105643539-bc286e80-5e90-11eb-943f-f5c2ab17366d.jpeg)
![WhatsApp Image 2021-01-11 at 13 30 14](https://user-images.githubusercontent.com/7694138/105643540-bcc10500-5e90-11eb-8091-3b7c997202b2.jpeg)

**Comment by Robkivit** [comment]
Martijn,
bedankt voor alle moeite!
Ik heb de instellingen voorzover mogelijk overgenomen in de camera’s

Als test heb ik een pushmelding aangezet voor ‘ camera terras’  en zal even checken of deze reageert op persoon of beweging. Ik heb hiervoor 2 flows gemaakt in homey

Nogmaals dank!

Met vriendelijke groet,
Rob Kivit

info@robkivit-natuurfotografie.nl <mailto:info@robkivit-natuurfotografie.nl>
www.robkivit-natuurfotografie.nl <http://www.robkivit-natuurfotografie.nl/>

**Comment by Robkivit** [comment]
Martijn,
Ik zie helaas nog steeds dat de app alleen reageert op de status beweging en niet op persoon 



Groeten, Rob

**Comment by Robkivit** [comment]
Martijn,
Moet ik de oude versie weer terugzetten en de logging uitzetten ?


Groeten, Rob

**Comment by martijnpoppen** [comment]
Hoi Rob,
Gek dat de camera niet reageert op persoons detectie. Krijg je wel persoonsdetectie via de Eufy app?

Je kan deze versie laten staan, deze gaat morgen live. Logging hoef je niet aan te laten staan tenzij je wilt dat ik er morgen nog naar kijk

**Comment by Robkivit** [comment]
Martijn,
Mmm..je triggered mij nu wel; in de app staat die op persoonsdetectie maar van de eufy app krijg ik een melding: Beweging gedetecteerd? Je zou verwachten dat je een melding zou verwachten zoiets als “persoon gedetecteerd” maar die melding heb ik nog nooit gezien. In dat geval zou er iets zijn met de eufy app..

Misschien heb jij nog een idee ?

In ieder geval bedankt dat je hier zoveel tijd hebt ingestoken!


Groeten, Rob

**Comment by martijnpoppen** [comment]
Rob,
Het enige wat ik kan bedenken is dat je `motion detection` aan heb staan en dat hij daardoor niet personen kan registreren. Ik heb zelf geen motion detecttion aan gezet aangezien hij overal op reageert.

Misschien werkt dat. Of je EufyCam2 hangt te ver weg om personen te kunnen registreren?
Check ook eens of je bij notification settings persons aan hebt staan.

Geen dank! Help graag

**Comment by Robkivit** [comment]
Martijn,
Bedankt!!


Groeten, Rob
