### ISSUE TITLE
[Feature Request] Preset response

### ISSUE THREAD

**Issue by MrBlue90** [martijnpoppen/com.eufylife.security#2]
Another thing that popped up my mind would be the integration of the preset audio responses.
Would be great if we could trigger these as an auto-response when someone presses the doorbell button.
Would this be feasible?
Cheers

**Comment by martijnpoppen** [comment]
I do have to check this. 
I don't own a Doorbell so it's a guessing job. Will look into this later.

**Comment by MrBlue90** [comment]
Sure, let me know in case I can support you in testing.
(And maybe with some donations we can even get you a doorbell if you like)

**Comment by martijnpoppen** [comment]
@MrBlue90 want to check this out. Maybe this works.
Do yo have any specific ideas about the implementation?.
We can also discuss on the community ofcourse

and yes the doorbell is on my list. 😄

**Comment by MrBlue90** [comment]
Ideas? Sure!
Implementation? Not yet since I didn't do a lot of investigation on the (sort of) API.

Since you don't own a doorbell, let me share a few screenshots with you:
On the camera page, there's a button for prefix responses:
![image](https://user-images.githubusercontent.com/11852942/105886653-f0c03580-600a-11eb-934b-6c62e21ecbfd.jpeg)

This opens a menu including 3 default responses (top 3) and a few that I created myself (bottom 3).
![image](https://user-images.githubusercontent.com/11852942/105886737-0d5c6d80-600b-11eb-8c48-50d2d74aae5b.jpeg)

From a Homey perspective, it would be awesome if we could create an action flowcard to trigger these.

The ultimate awesomeness would be sending custom audio files to the doorbell which would be played, but I don't expect this will ever be possible.

**Comment by martijnpoppen** [comment]
Alright!
Do you know if there's an limit on the custom audio presets?
I did already find an way to trigger them. So it's just finding out what to send

**Comment by MrBlue90** [comment]
Awesome!!
Yes, you can only create 3 custom responses. Including the 3 default ones, that makes 6.
Could you query the names and list them in a dropdown for the flowcard?

**Comment by martijnpoppen** [comment]
I think it will just look like:

`Default response 1`
`Default response 2`
`Default response 3`
`Custom response 1`
`Custom response 2`
`Custom response 3`

**Comment by MrBlue90** [comment]
Could be a good start as well, not sure what will happen to the order if you start messing with the responses though.

Let me know if you want me to test something.

**Comment by martijnpoppen** [comment]
Check, you have the doorbell 2k battery right?

**Comment by MrBlue90** [comment]
Yes, T8210 to be exact

**Comment by martijnpoppen** [comment]
Alright, I put a version in test.
There's a quick menu from the device itself. Same tab as Arming mode.
Also possible to trigger as an action :)

**Comment by martijnpoppen** [comment]
![Screenshot_20210126-204516](https://user-images.githubusercontent.com/7694138/105896726-7813a600-6017-11eb-99b8-0d3600199d47.jpg)

**Comment by MrBlue90** [comment]
Just tried the flowcard, but getting an error:
![image](https://user-images.githubusercontent.com/11852942/105897053-f112fd80-6017-11eb-99cc-1537da0592d5.png)

**Comment by martijnpoppen** [comment]
hmm will look into that, can you try it via the device menu?

**Comment by martijnpoppen** [comment]
Fixed the flowcard. 
Updated to 1.8.8

**Comment by MrBlue90** [comment]
Tried 1.8.8
Flow runs, but nothing happens on the doorbell side.
Same for device setting.

**Comment by martijnpoppen** [comment]
Hmm alright.
I tried sending the command. With the correct code, but I should also send and index/identifier of the quickresponse. Not sure what that should be 😞

**Comment by martijnpoppen** [comment]
An extra check. 
If you turn the doorbell on/off via Homey. Doest it show as on/off in your Eufy app?

**Comment by MrBlue90** [comment]
Could you send me the API calls that you're using? Then I can give it a try and see if I receive any useful response.

Turning on/off the doorbell works.

**Comment by martijnpoppen** [comment]
I'm not using API calls. I'm using P2P commands from the library. using HTTP doesn't work.

What you could check:

- trigger an quick response 
- call the POST login url (shared with you in the community)
- call POST https://mysecurity.eufylife.com/api/v1/app/get_devs_list (with headers x-auth-token: YOUR_TOKEN)

do this multiple times and compare the params arrray.
Maybe in that way we can determine which param it is and what kind of value we should send.

If we have that we can put that in the P2P command and it should work.
This API is basically APP behaviour. So it only shows data but doesn't consume it.

**Comment by martijnpoppen** [comment]
Tool to check diffs: https://www.diffchecker.com/

**Comment by martijnpoppen** [comment]
Forgot to add, but trigger the quick response from the official app. As we don't know if the current implementation works

**Comment by MrBlue90** [comment]
Testing this right now, but only get back:

`{
    "code": 0,
    "msg": "Succeed."
}`

Feel like I'm not looking at the correct data...

**Comment by martijnpoppen** [comment]
That's not correct.
It should look like this:

```{
    "code": 0,
    "msg": "Succeed.",
    "data": [
        {
            "device_id":`
            ```

**Comment by MrBlue90** [comment]
Yep, that's what I was expecting as well..
Doubted whether I was using the correct auth code, but changing that one resulted in no response at all..
Not sure what's causing this lack of data, but will have a look at it later today.

**Comment by martijnpoppen** [comment]
Seems like this works. As stated in the community/
Will continue the conversation there and close this topic 😄
