### ISSUE TITLE
Kan camera niet installeren

### ISSUE THREAD

**Issue by Johannes-Verdi** [martijnpoppen/com.eufylife.security#20]
Ik probeer een pan & tilt camera te installeren in homey.bij het ingeven van de accountgegevens krijg ik de melding dat er een code nodig is. Ik heb de accountgegevens van de eufy App ook in homey gebruikt. Er kunnen ook geen camera's gevonden worden als ik deze toe wil voegen Help!

**Comment by martijnpoppen** [comment]
Hoi Johannes,
Als het goed is heb je een 2e account aangemaakt in de Eufy app en die rechten gegeven om je camera's te mogen bekijken. Zo niet zou ik je aanraden dit te doen, aangezien Eufy je anders kan blokkeren. 

Zorg ervoor dat je 2e acocunt geen 2FA (Two Factor Authenticaiton) aan heeft staan. Op dit moment werkt dat niet in de Homey app.

Als je deze stappemn doorloopt zul je je Pan&Tilt kunnen vinden in de Homey app.

**Comment by martijnpoppen** [comment]
Het aanmaken van een extra (admin) account doe je in de Eufy app.

Ga naar family & guests en nodig daar een extra gebruiker uit.
Vervolgens maak je een nieuw account aan met die gebruiker en log daarmee in in de Eufy app. Zodra je ingelogd bent krijg je de uitnodiging uit je hoofd account te zien.
Accepteer die en je zal je apparaten zien.

Log vervolgens weer uit bij de Eufy app.

Nu kan je dat extra account gebruiken in de Homey-Eufy app.

**Comment by Johannes-Verdi** [comment]
Beste Martijn,

Ik heb via mijn tweede emailadres een uitnodiging verzonden. Ik kom echter
niet op het punt dat k in kan loggen met dit tweede account. De Eufy App
die op mijn telefoon staat, heeft natuurlijk al een account. Moet k de app
twee keer installeren?

Met vriendelijke groet,

Hans Groenen

Op wo 20 jan. 2021 16:58 schreef Martijn Poppen <notifications@github.com>:

**Comment by martijnpoppen** [comment]
Beste Hans,
In dit geval zal je moeten uitloggen in de Eufy app. Inloggen met de het nieuwe account en dan nadat je de uitnodiging heb geaccepteerd weer uitloggen

**Comment by Johannes-Verdi** [comment]
Ga ik proberen, dank voor je zeer snelle reactie!

Met vriendelijke groet,

Hans Groenen

Op wo 20 jan. 2021 19:20 schreef Martijn Poppen <notifications@github.com>:

**Comment by Johannes-Verdi** [comment]
Heel stom misschien, maar ik kan niet uitloggen? Als k me afmeld, start
eufy gewoon weer op met mijn oorspronkelijke account.....

Met vriendelijke groet,

Hans Groenen

Op wo 20 jan. 2021 19:21 schreef Hans Groenen <johannes.verdi@gmail.com>:

**Comment by martijnpoppen** [comment]
Onderin staat another account'

**Comment by Johannes-Verdi** [comment]
Ja, gelukt, dank voor je geduld en snelle reacties, super! Zou ik nu in
Homey ook de camerabeelden moeten kunnen zien, want hier krijg ik, ook
nadat de camera heb aangezet (werkt prima), een standaard voorzetscherm.

Met vriendelijke groet,

Hans Groenen

Op wo 20 jan. 2021 19:36 schreef Martijn Poppen <notifications@github.com>:

**Comment by martijnpoppen** [comment]
Op het moment dat er vanuit Eufy een notificatie wordt aangeroepen (beweging/deurbel druk/persoons detectie) zal die afbeelding geupdatet worden.
Homey ondersteund geen video streams alleen snapshots/afbeeldingen.

Als je een flow als volgt hebt zal de afbeelding geupdated worden zodra je apparaat een van bovenstaande detecties heeft.

<img width="317" alt="image" src="https://user-images.githubusercontent.com/7694138/105221210-16f05c00-5b59-11eb-9970-7de8d3b9a8e9.png">

**Comment by Johannes-Verdi** [comment]
OK, helder. Nogmaals heel veel dank!

Met vriendelijke groet,

Hans Groenen

Op wo 20 jan. 2021 19:53 schreef Martijn Poppen <notifications@github.com>:

**Comment by martijnpoppen** [comment]
Geen probleem!
Mocht je nog meer vragen hebben weet je mij te vinden.
Er is ook een community topic voor de app: https://community.athom.com/t/eufy/30479
Hierin plaats ik ook berichten wanneer er een update is.

**Comment by Johannes-Verdi** [comment]
Dag Martijn,

Wij hadden eerder contact over het integreren van de Eufy camera in Homey.
Op jouw aanwijzingen is dat inmiddels gelukt, waarvoor nogmaals dank. Het
lijkt echter niet mogelijk om de camera aan en uit te schakelen vanuit
Homey (ik heb een flow waarin afwezigheid de trigger is voor een aantal
acties).
Klopt dit of ben ik weer onhandig bezig?
Alvast bedankt voor je antwoord.

Met vriendelijke groet,

Hans Groenen

**Comment by martijnpoppen** [comment]
Hallo @Johannes-Verdi ,
Dat zou wel moeten werken. Het ging om een pan&tilt toch?
Ik had laatst ook iemand die daar problemen mee had. Een restart van de app was voldoende hiervoor .

Zou je je flow kunnen delen?

Groet Martijn

**Comment by Johannes-Verdi** [comment]
Ik wil mijn flow wel delen hoor, maar ik kan de camera ook niet 'handmatig'
aan en uit zetten vanuit Homey.

Met vriendelijke groet,

Hans Groenen

Op do 1 apr. 2021 16:59 schreef Martijn Poppen ***@***.***>:

**Comment by martijnpoppen** [comment]
Krijg je een error message te zien?
Kan je kijken bij de apparaat instellingen of hij op "altijd aan" staat?

**Comment by Johannes-Verdi** [comment]
Klopt inderdaad, ik krijg een 'timed out' foutmelding...... Owkee, wat deed
ik fout?

Met vriendelijke groet,

Hans Groenen

Op do 1 apr. 2021 17:34 schreef Martijn Poppen ***@***.***>:

**Comment by martijnpoppen** [comment]
Zou je kunnen controleren of je op adres bij de app instellingen een intern ip adres is?

Het ip adres van je camera/Homebase kan je vinden bij About device in de Officiële Eufy App.

Als je die hebt dan kan je die invullen in de app instellingen

**Comment by Johannes-Verdi** [comment]
Het IP-adres scheelde één cijfertje, een 6 IPV een 5.
Hoe stom kun je zijn? SORRY en wederom bedankt!

Met vriendelijke groet,

Hans Groenen

Op do 1 apr. 2021 17:40 schreef Martijn Poppen ***@***.***>:

**Comment by Johannes-Verdi** [comment]
Werkt als een zonnetje, heel blij mee!

Met vriendelijke groet,

Hans Groenen

Op do 1 apr. 2021 17:48 schreef Hans Groenen ***@***.***>:

**Comment by martijnpoppen** [comment]
Geen probleem blij dat het werkt!
