### ISSUE TITLE
no video - Eufycam 1

### ISSUE THREAD

**Issue by ellekebelleke** [martijnpoppen/com.eufylife.security#31]
Hello Martijn,
Any tips on how to get the video in Homey working for Eufy Cam 1?

**Comment by martijnpoppen** [comment]
Hi @ellekebelleke ,
Currently there's no way to get live video.
Only thing thing that's supported is the last motion event. 
If you experience issues with the image of the last motion event, I would suggest to restart the app. That will solve it most of the times.

**Comment by ellekebelleke** [comment]
Hi @martijnpoppen 
Ok, that's clear. Thanks.
I do have issues with the image. I can only see the default image, no image capture from the cameras.  I've tried restarting several times.

**Comment by martijnpoppen** [comment]
Hi @ellekebelleke ,
Do you get notifications from your camera?
Make sure the notifications are enabled in your eufy app and they have use the `include thumbail` mode.
In that case Homey can catch those notifications. Homey is like an extra Phone with an Eufy app in this case :)
