### ISSUE TITLE
Feature request: Homebase Chime as action

### ISSUE THREAD

**Issue by MrBasque** [martijnpoppen/com.eufylife.security#41]
Is there a possibility to let the Homebase ring ? (chime like doorbell)?

I would to use in one of my flows: 
when somebody enters the backdoor (sensor)
then play a sound om my homebase (like the chime when doorbell rings)

**Comment by martijnpoppen** [comment]
Hey @MrBasque ,
No this is not possible as this is working in the internal flows of Eufy and can not be exposed to Homey

**Comment by MrBasque** [comment]
Too bad, thanks!
