### ISSUE TITLE
Feature request: Make a photo(snapshot) with cam

### ISSUE THREAD

**Issue by MrBasque** [martijnpoppen/com.eufylife.security#42]
Would like to be able to make a photo (snapshot) with the doorbell camera or eufy-cam so I can use it in my flows.

Currently a snapshot is only provided on movement detection or doorbell press,

**Comment by martijnpoppen** [comment]
As mentioned over here https://community.athom.com/t/app-pro-eufy-security/44921/4?u=martijnpoppen

It's not possible to do that.
This is not an official implementation of Eufy
