### ISSUE TITLE
Snapshot

### ISSUE THREAD

**Issue by schliemann** [martijnpoppen/com.eufylife.security#43]
Hi @martijnpoppen,

Just stumbled over your changes to the eufy-node-client library. And out of curiosity I wanted to ask you if you had found a way to tell the camera to make a new snapshot without starting a live stream. I know it is possible since the eufy Homekit integration features this as seen here:

https://user-images.githubusercontent.com/10818044/150146251-55b87064-c961-4353-a2fe-1c2a4007b602.mp4

**Comment by martijnpoppen** [comment]
Hey @schliemann ,
No I didn't find a way to do that. It's only possible if you can run FFMPEG. But for the Homey integration that's not possible. (Homey can't process that).

**Comment by schliemann** [comment]
Ah. Had a small hope 😅.

**Comment by martijnpoppen** [comment]
You might want to look at eufy-security-client. But I think you forked that already :P

**Comment by schliemann** [comment]
Yeah. Already using that for our homebridge plugin.
