### ISSUE TITLE
Snooze not effective on 2k powered doorbell

### ISSUE THREAD

**Issue by rnldnkp** [martijnpoppen/com.eufylife.security#44]
Using a wired (powered) 2K doorbell and Homey Eufy App 2.27.8
Tried a test flow to enable Snooze mode on this doorbell.
Choose in the then column 'Snooze mode for'
The only setting I have is the duration, I choose: 1 hour

Once I run the flow the iPhone App does show the blue "doorbell Zzz" sign.
But when pressing the doorbell it still rings the indoor receiver like before.

Then tried the same function in the iPhone App.
You push the doorbell sign with Zzz next to it and have to choose:
1. Snooze motion (tickbox)
2. Snooze doorbell receiver (inside chime) (tickbox)
3. Time 30m, 1h, 2h, 6h, 12u in a list. Have to tick the one you want

If selected only the duration you cannot save.
You have to select the duration and choose at least one tickbox.
When I select 'snooze doorbell receiver' + 30min in the iPhone app it works as designed.

My expectation is this should both work the same in the iPhone app and trough the Homey App.

My guess is, the tickbox to snooze either motion or receiver (or both) is missing.
Somehow it does enable snooze but without 'what' to snooze.

Why I think so? Because I compared it with the normal 2K Eufy Cam that does not have the tickboxes, you can only choose for a duration. BTW the whole iPhone App interface is different (durations are in a grid) compared to the doorbell.

I did try and check the main device driver file to see how this works in the app.
There I see only one function to enable snooze. Is seems to mention "chime_onoff" on line 508 but it's always set to 0. There no integer like the other options. Not sure this is designed for the same thing as I'm asking, but it does look like it ;)

https://github.com/martijnpoppen/com.eufylife.security/blob/22b7d3de9d4efcfe0ededd3db2b7ca6beaac96d9/drivers/main-device.js#L496-L518 

I hope this can be fixed.
Would love to snooze the doorbell when the baby is asleep.
Turning it off is another option but that turns off everything...
For who is interested, once snooze is working, this also works for homebridge in combination with HomePods. Your homepods will not ring during this period.

Thanks in advance for looking in to this!

**Comment by martijnpoppen** [comment]
Hey @rnldnkp 
Sounds like a valid point.

Can you share a screenshot of the snooze settings for the doorbell?

For the Battery doorbell I have the following: 
![image](https://user-images.githubusercontent.com/7694138/153506276-cf9810d8-9d90-4c4a-af51-44a42c4bb697.png)


I can make the update for the chime_onoff. But have to check to make it backwards compatible :) 
Don't want to brick other peoples implementation :P

**Comment by martijnpoppen** [comment]
@rnldnkp So I already made a fix. Based on your post I think it almost works the same as the Homebase based devices except instead of Homebase it uses Chime.

You can install the test version here: https://homey.app/nl-nl/app/com.eufylife.security/Eufy-Security/test/


Link to the forum changelog: (i share all updates there)
https://community.homey.app/t/app-pro-eufy-security/44921/2109?u=martijnpoppen

**Comment by rnldnkp** [comment]
Wow, you are very quick with the fix!
Did a quick test this morning and it seems to work right away! (of course after re-adding the device to Homey since you changed a capability/flowcard)

Will make the flows I had in mind this weekend.
If anything comes up I will keep you posted.

Thanks!

**Comment by martijnpoppen** [comment]
Hey awesome
Yes let me know 
Re-adding was nog necessary. Flowcards are added / removed automativally
