### ISSUE TITLE
API related issue

### ISSUE THREAD

**Issue by tmsblgh** [martijnpoppen/com.eufylife.security#54]
I added a Eufy Indoor Cam 2K Pan & Tilt but it not works properly. The error message:

Eufy made changes to their API
Currently it's not possible to retrieve camera thimbnails from the Eufy devices in Homey.

**Comment by martijnpoppen** [comment]
Hey yes that's intended. I made that image 😉 
For more info go to: https://community.homey.app/t/app-pro-eufy-security/44921/4?u=martijnpoppen
