### ISSUE TITLE
Feature request: Enable/disable doorbell notifications

### ISSUE THREAD

**Issue by terryhendrix1990** [martijnpoppen/com.eufylife.security#56]
Please report your issue at https://community.homey.app/t/app-pro-eufy-security/44921

I thought it would be great if Eufy could only send me a notification if some is at the door when I'm not home. Is this something that could be set with the javascript client?

**Comment by martijnpoppen** [comment]
Hi 
As mentioned please request at the forum.

**Comment by martijnpoppen** [comment]
Also, thats why there are security modes in Eufy. And those are already supported in Homey
