### ISSUE TITLE
LOCAL_STATION_IP uses external IP and gets timeout

### ISSUE THREAD

**Issue by mathieudebrito** [martijnpoppen/com.eufylife.security#6]
**Thanks**
First of all, THANK YOU for this Homey app !
I just started creating one when I found your already ready and well coded app :)

**Context**
So I first installed the app via https://store.homey.community/app/com.eufylife.security, tested it and it failed :( 
So I downloaded the code, ran the app using the CLI and saw this error in the logs : 
```
[error] Timeout on address: xxx.xxx.xxx.xxx
```
So I changed some code to force the LOCAL_STATION_IP to the IP of the station in my local lan and it worked :
```
[log] devClientService - Initializing...
[log] devClientService - Found IP address { host: 'xxx.xxx.xxx.xxx', port:xxxxx }
[log] devClientService - Connected
```

**Possible solution**
I think it may be helpful to let the user be able to change the IP manually.

**Comment by martijnpoppen** [comment]
Hi Mathieu,
Good catch.
I'll put this on top of the list :) 

Thanks!
