### ISSUE TITLE
Camera Eufy Cam E not recognized ?

### ISSUE THREAD

**Issue by mathieudebrito** [martijnpoppen/com.eufylife.security#7]
**Context**
The app is logged to the station
```
[log] devClientService - Initializing...
[log] devClientService - Found IP address { host: 'xxx.xxx.xxx.xxx, port: xxxx }
[log] devClientService - Connected
[log] Registered at pushService with: ...
```
but when I try the add a flow and select a device, it found no device :
```
[log] Found devices -  []
```

**Possible Solution**
Add the Eufy Cam E in the device type list and add the corresponding driver:
```
exports.DeviceType = {
...
  EUFYCAM_E: 'T8112',
...
}
```

I just tried to add the deviceType, driver and update the `app.js` but it does not work:
```
[log] Found devices -  []
onSocketError:  Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
```
But I may have forgotten something, do you have any idea ? 
Don't hesitate to send me homework, if I can help, I will !

**Comment by martijnpoppen** [comment]
Hi @mathieudebrito ,
Correct you should add the device first to your Homey.
For now you can chose any devices. All the drivers are the same.
Then in the flow you can find it

Currently i'm changing to device only flows. Hopefully in the next release :)

**Comment by martijnpoppen** [comment]
I Will add the devices to the list. :)

**Comment by mathieudebrito** [comment]
Haha That's really great, thank you !
I did not even imagine that we could add the camera as Homey devices, that's really wonderful, thank you :D 

To follow up, I just added the devices, created a flow to ON one of my camera but did not work :p

I saw this in the logs : 
```
[log] Connected to P2P service -  3000
[log] Sending Command with IntString - CMD_DEVS_SWITCH : 1
```

Thank you very much again for your work, I will definitely buy you a beer or two ;)

**Comment by martijnpoppen** [comment]
Yes that's correct.
It sends a command to the device.
If you turn it off you'll see in the eufy app that its turned of

**Comment by mathieudebrito** [comment]
@martijnpoppen Hello ! 

I just tested again, it seems you already greatly improve the devices :)

i added the devices, but if I try to set turn them on / off, I get this multiple times : 
```
onSocketError:  Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
```
I'm a bit stuck at this, so do you have any idea please ?

I also got this one time, I'm not sure if it can interest but, so just in case :
```
(node:31439) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'isConnected' of undefined
    at /lib/helpers/eufy-command-send.helper.js:46:30
    at new Promise (<anonymous>)
    at Object.exports.sendCommand (/lib/helpers/eufy-command-send.helper.js:45:12)
    at device_EUFYCAM_E.onCapability_CMD_DEVS_SWITCH (/drivers/main-device.js:20:41)
    at device_EUFYCAM_E.__onCapability (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Device.js:1:2100)
    at device_EUFYCAM_E.emit (events.js:311:20)
    at driver_EUFYCAM_E.__onCapability (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Driver.js:1:1718)
    at driver_EUFYCAM_E.emit (events.js:311:20)
    at /opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/manager/drivers.js:1:1457
    at SDK._onReady (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/SDK.js:1:1034)
(node:31439) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:31439) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by martijnpoppen** [comment]
Yeah i had that too, but that should be fixed in v1.3.2
Are you running that version?

**Comment by martijnpoppen** [comment]
FYI  there's a community topic with more people testing. If you want to see what other people are testing :)

https://community.athom.com/t/eufy/30479/80

**Comment by mathieudebrito** [comment]
Yes, I run the app directly from the sources (via `homey app run`), I still checked and run the 1.3.2 don't hesitate to ask for any more details ;)

Perfect for the community topic thank you, talk to you there then !

**Comment by martijnpoppen** [comment]
The isconnected part is coming from the devClientService which should initialized when you start the app or update your credentials. Will check that part.

**Comment by martijnpoppen** [comment]
Technical issues you can post here. Just an FYI 😄

**Comment by martijnpoppen** [comment]
@mathieudebrito Just pushed a fix for the `IsConnected()` to `main` branch

**Comment by mathieudebrito** [comment]
@martijnpoppen It works great thank you !
I can now enable/disable my camera, that's awesome, thank you !

Just one last thing :p

All my camera were disabled. 
I created a flow to enable one of my camera and ran it.
My camera did not enable.

After debugging it, I understood that for my camera, the command sent were switched (enable = disable and vice versa)
```
- Command to Enable :
[log] Connected to P2P service -  1000
[log] Sending Command with IntString - CMD_DEVS_SWITCH : 1
-> result not enabled

- Command to switch
[log] Connected to P2P service -  2500
[log] Sending Command with IntString - CMD_DEVS_SWITCH : 0
-> it sent 0, so it enabled

- Command to disable
[log] Connected to P2P service -  3000
[log] Sending Command with IntString - CMD_DEVS_SWITCH : 0
-> it enabled the camera
```

Hope it helps :)

Thank you again, it's beer time !

**Comment by martijnpoppen** [comment]
Nice!
You can also add a event for your camera. So if 'motion detected' then alert me. Or something like that.

and i read that somewhere that the 0 and 1 were switched. But for my cam it isn't.
Will write a mapping object for that :) 

And thanks for the coffees/beers! 😄

**Comment by mathieudebrito** [comment]
Awesome, I will try that :D

Thank you again, Don't hesitate to tag me if you need any help !
